name: DevSecOps-Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # -------------------------------
      # 1) DOCKER LOGIN (OPTIONAL BUT RECOMMENDED)
      #
      # This step only helps if you have a Docker Hub account with
      # DOCKER_USERNAME and DOCKER_PASSWORD stored in GitHub Secrets.
      # Without login, you may get "pull access denied" if you're hitting
      # Docker's anonymous rate limits or IP blocks.
      # -------------------------------
      - name: Docker login
        run: |
          if [ -n "${{ secrets.DOCKER_USERNAME }}" ] && [ -n "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
              --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            echo "Docker login successful."
          else
            echo "No Docker credentials provided; pulling anonymously."
          fi

      # Step 2: Build Docker image of your app
      - name: Build Docker image
        run: |
          docker build -t minimal-devsecops-example .

      # Step 3: Scan Docker image with Trivy
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'minimal-devsecops-example'
          exit-code: '0'  # Set to '1' if you want the build to fail on any vulnerability

      # Step 4: Run container in background
      - name: Run container
        run: |
          docker run -d -p 8080:8080 --name minimalapp minimal-devsecops-example

      # Step 5: OWASP ZAP Baseline Scan
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          # Where ZAP should scan
          target: 'http://127.0.0.1:8080'
          #
          # In v0.7.0, must be 'true' or 'false'
          fail_action: 'false'
          #
          # The CORRECT Docker image name on Docker Hub is "owasp/zap2docker-weekly"
          # (No colon! This is the repo name. The tag is "latest" by default.)
          docker_name: 'owasp/zap2docker-weekly'
          #
          # Allows the action to create GitHub issues, etc.
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Stop the container
      - name: Stop container
        run: docker stop minimalapp
