name: DevSecOps-Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # Step 1: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t minimal-devsecops-example .

      # Step 2: Container Image Scan with Trivy
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'minimal-devsecops-example'
          exit-code: '0'  # Change to '1' if you want to fail when vulnerabilities are found

      # Step 3: Run the container in background
      - name: Run container
        run: |
          docker run -d -p 8080:8080 --name minimalapp minimal-devsecops-example

      # Step 4: OWASP ZAP Baseline Scan
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://127.0.0.1:8080'
          fail_on_error: false   # If true, the pipeline fails on any ZAP alerts

      # Step 5: Stop the container
      - name: Stop container
        run: docker stop minimalapp
