name: DevSecOps-Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # (Optional) Docker login to avoid "pull access denied" or rate-limiting
      - name: Docker login
        run: |
          # Only runs if DOCKER_USERNAME and DOCKER_PASSWORD secrets are defined
          if [ -n "${{ secrets.DOCKER_USERNAME }}" ] && [ -n "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
              --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            echo "Docker login successful."
          else
            echo "No Docker credentials provided, skipping login."
          fi

      # Step 1: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t minimal-devsecops-example .

      # Step 2: Scan Docker image with Trivy
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'minimal-devsecops-example'
          exit-code: '0'  # change to '1' if you want to fail on detected vulnerabilities

      # Step 3: Run container in background
      - name: Run container
        run: |
          docker run -d -p 8080:8080 --name minimalapp minimal-devsecops-example

      # Step 4: OWASP ZAP Baseline Scan
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://127.0.0.1:8080'
          # Valid in v0.7.0 => 'true' or 'false' (no "warn" or "ignore")
          fail_action: 'false'
          # IMPORTANT: Use the correct official ZAP image:
          docker_name: 'owasp/zap2docker-weekly'
          # or 'owasp/zap2docker-stable' if you want the stable release
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Stop the container
      - name: Stop container
        run: docker stop minimalapp
