name: DevSecOps-Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # Step 0 (Optional): Docker login to avoid "pull access denied" or rate-limits
      - name: Docker login
        run: |
          if [ -n "${{ secrets.DOCKER_USERNAME }}" ] && [ -n "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
              --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            echo "Docker login successful."
          else
            echo "No Docker credentials provided, skipping login."
          fi

      # Step 1: Build Docker image
      - name: Build Docker image
        run: docker build -t minimal-devsecops-example .

      # Step 2: Container Image Scan with Trivy
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'minimal-devsecops-example'
          exit-code: '0'    # Set to '1' if you want to fail on vulnerabilities

      # Step 3: Run the container in the background
      - name: Run container
        run: docker run -d -p 8080:8080 --name minimalapp minimal-devsecops-example

      # Step 4: OWASP ZAP Baseline Scan
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://127.0.0.1:8080'
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_action: 'false'   # Must be 'true' or 'false' in v0.7.0
          docker_name: 'owasp/zap2docker-stable'

      # Step 5: Stop container
      - name: Stop container
        run: docker stop minimalapp
